### ISSUE TITLE
Allow user to specify queries in validation sampling

### ISSUE THREAD

**Issue by stsievert** [stsievert/salmon#114]
It'd be nice if the user could specify the target indices a user asks about. i.e.,

``` yaml
targets: ["a", "b", "c", "d", "e"]
samplers:
  ValidationSampling: {queries: [(0, 1, 2), (1, 2, 3), (2, 3, 4)]}
```

would show these targets to the user:

*  `["a", "b", "c"]` (via target indices 0, 1, 2)
* `["b", "c", "d"]` (via target indices 1, 2, 3)
* `["c", "d", "e"]` (via target indices 2, 3, 4)

cc @kushinm
