### ISSUE TITLE
Invalid YAML file to /init_exp throws "iternal service error"

### ISSUE THREAD

**Issue by stsievert** [stsievert/salmon#12]
Let's say I upload this YAML file to `/init_exp`:

``` yaml
targets:
  -\tWithin
  -\tZigzag
instructions: Which word on the bottom is most similar in meaning to the top word?
max_queries: 200
debrief: Thanks for your participation!
```

Here, the `\t`s mean "tab character".

This throws an "Internal service error" on the frontend.
