### ISSUE TITLE
Defaults not suitable for experimentalists

### ISSUE THREAD

**Issue by stsievert** [stsievert/salmon#124]
A core competency of Salmon is active sampling. However, using active sampling requires significant editing of the parameters; they currently default to the `Random` sampler (the most basic sampler). It also has `samplers_per_user=0` by default, which again might not be the best choice for experimentalists (they don't want any intermixing between crowdsourcing users).

The current defaults:

https://github.com/stsievert/salmon/blob/afe2cd9e5501e5a4020c2294d59660c6ef02cdec/salmon/frontend/private.py#L300-L309

Right now, these require significant editing by the experimentalist.

| Parameter | Edits required by experimentalists |
|------:|:---------|
| html.instructions | Requires editing (no `<i>arbitrary html</i>`) |
| html.debrief | No note about participant ID being shown below the note |
| samplers | Requires editing for use of active samplers (the whole reason for writing Salmon) |
| sampling | Will require editing to get correct train/test split |
| html.max_queries | Requires editing to show the debrief |

Related: https://github.com/stsievert/salmon/issues/121#issuecomment-953314787 (which mentions changing the default for `html.arrow_keys`).

**Comment by stsievert** [comment]
I think a better set of defaults is:

* max_queries: 50 or 100
* html.instructions: Please select the comparison item that is most similar to the target.
* html.debrief: Thanks! Please use the participant ID below:

I'm still a little divided on defaults for `samplers`. I think the FAQs ["How many responses will be needed?"][1] and ["What active samplers are recommended?"][2] (updated in #123).

[1]"https://docs.stsievert.com/salmon/faq.html#how-many-responses-will-be-needed
[2]:https://docs.stsievert.com/salmon/faq.html#what-active-samplers-are-recommended

**Comment by crcox** [comment]
This might be it's own issue, but I am confused about how the defaults interact with the `yaml` configuration file when determining the dimensions for embedding. The example in the Docs says that modifying `samplers: common: d` will do the trick... but I just noticed in the dashboard that it was still saying d=2 when I specified d=5. When I download the YAML from the dashboard, I see:

```
d: 2
html:
  arrow_keys: true
  css: ''
  debrief: Thank you for completing this portion of our study! Please copy the completion
    code below and paste it into the box provided on the page that linked you to this
    task.
  instructions: Select the option that depicts the scene most similar to the reference
    image.
  max_queries: 100
  skip_button: false
n: 680
samplers:
  ARR:
    random_state: 8581
  Random: {}
sampling:
  common:
    d: 5
  probs:
    ARR: 85
    Random: 15
  samplers_per_user: 0
targets:
<truncated>
```

There is a `d:` at the top level, as well as the `d` under `sampling common`. I am worried that this default `d` is dominating.
